name: Deploy Node.js App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.11.0

    - name: Deploy to AWS EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        # Save the EC2 private key from GitHub Secrets
        echo "${{ secrets.EC2_SSH_KEY }}" > revision.pem
        chmod 600 revision.pem
        
        # EC2 Public IP
        EC2_PUBLIC_IP=13.127.85.156

        # Ensure we're in the correct directory
        echo "Current directory:"
        pwd
        echo "Listing files:"
        ls -la

        # Copy project files to the EC2 instance
        scp -o StrictHostKeyChecking=no -i revision.pem -r ./samplenodeapp ubuntu@$EC2_PUBLIC_IP:/var/www/geetha.com

        # SSH into the EC2 instance and deploy the application
        ssh -o StrictHostKeyChecking=no -i revision.pem ubuntu@$EC2_PUBLIC_IP << EOF
          cd /home/ubuntu/samplenodeapp
          npm install
          pm2 restart samplenodeapp || pm2 start app.js --name "samplenodeapp"
        EOF

    - name: Clean up
      run: rm -f revision.pem
